# Use an official Node.js runtime as a parent image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy all other source code to the working directory
COPY ./sslFiles ./sslFiles
COPY ./index.js ./index.js

# Start the server
CMD ["npm", "start"]
